export const defaultClearanceData = {
  courtName: "REGIONAL TRIAL COURT",
  judicialRegion: "5th Judicial Region",
  courtCity: "Iriga City",
  courtEmail: "rtc1iriocc@judiciary.gov.ph",
  courtTel: "(054)299-5922",
  fullName: "",
  nationality: "",
  civilStatus: "",
  dob: "",
  address: "",
  finding: "NO DEROGATORY RECORD FOUND",
  purpose: "",
  givenDay: "",
  givenMonth: "",
  givenYear: "",
  givenPlace: "",
  clerkName: "HARLETTE R. ARROYO-POTENCIO",
  clerkTitle1: "Clerk of Court VI",
  clerkTitle2: "Ex-Officio Provincial Sheriff & Notary Public",
  assistantClerkName: "",
  assistantClerkTitle: "",
  stampOR: "",
  stampDate: "",
  orNo: "",
  orDate: "",
  ctc: "",
  issuedAt: "Iriga City",
  issuedOn: "",
  certNo: "",
  noteText: "Valid for 6 months from the date of issue.",
  noteInitials: "MBL/jnr"
};
