export const defaultClearanceData = {
  courtName: "REGIONAL TRIAL COURT",
  judicialRegion: "5th Judicial Region",
  courtCity: "Iriga City",
  courtEmail: "rtc1iriocca@judiciary.gov.ph",
  courtTel: "(054)299-5922",
  fullName: "",
  nationality: "",
  civilStatus: "",
  dob: "",
  address: "",
  finding: "",
  purpose: "",
  givenDay: "",
  givenMonth: "",
  givenYear: "",
  givenPlace: "",
  clerkName: "HARLETTE R. ARROYO-POTENCIO",
  clerkTitle1: "Clerk of Court VI",
  clerkTitle2: "Ex-Officio Provincial Sheriff & Notary Public",
  assistantClerkName: "",
  assistantClerkTitle: "",
  stampOR: "",
  stampDate: "",
  orNo: "",
  orDate: "",
  ctc: "",
  issuedAt: "",
  issuedOn: "",
  certNo: "",
  noteText: "",
  noteInitials: "MBL/jnr"
};
